---
collections:
  - name: ansible.platform
  - name: ansible.hub
  - name: ansible.controller
  - name: ansible.eda
  - name: ansible.posix
  - name: infra.aap_configuration
  - name: infra.aap_utilities
  - name: kubernetes.core
  - name: redhat.openshift
...
