---
all:
  children:
    stage:
      hosts:
        stage-aap-vvaldez-aap-stage.apps.cluster-29pl9.dynamic.redhatworkshops.io:
  vars:
    aap_env: 'stage'
    # install vars
    aap_ocp_install_namespace: vvaldez-aap-stage
    aap_ocp_install_operator:
      channel: "stable-2.6"
    aap_ocp_install_platform:
      instance_name: stage-aap
    aap_ocp_install_controller:
      install: true
    aap_ocp_install_eda:
      install: true
    aap_ocp_install_hub:
      install: true
      storage_type: file
      file_storage_size: 100Gi
      file_storage_storage_class: ocs-external-storagecluster-cephfs
    aap_ocp_install_lightspeed:
      install: true
    # post-install configuration vars
    aap_hostname: stage-aap-vvaldez-aap-stage.apps.cluster-29pl9.dynamic.redhatworkshops.io

...
